// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9QWf55kiCUBJBqWCv2clhL-DAp2PIHcg',
    appId: '1:101206721106:web:b6b053d0612d93d82b158b',
    messagingSenderId: '101206721106',
    projectId: 'project-7eb26',
    authDomain: 'project-7eb26.firebaseapp.com',
    storageBucket: 'project-7eb26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtnblb6RAYieDFsIWz-LrtE-XWP6bphvA',
    appId: '1:101206721106:android:7f448706f7837f972b158b',
    messagingSenderId: '101206721106',
    projectId: 'project-7eb26',
    storageBucket: 'project-7eb26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-wNj-x78Nwpy_V-RTym6zK4ntQt-cmsg',
    appId: '1:101206721106:ios:61d1a9142e9ef14b2b158b',
    messagingSenderId: '101206721106',
    projectId: 'project-7eb26',
    storageBucket: 'project-7eb26.appspot.com',
    iosBundleId: 'com.example.pewterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-wNj-x78Nwpy_V-RTym6zK4ntQt-cmsg',
    appId: '1:101206721106:ios:76c93ce069ed365e2b158b',
    messagingSenderId: '101206721106',
    projectId: 'project-7eb26',
    storageBucket: 'project-7eb26.appspot.com',
    iosBundleId: 'com.example.pewterApp.RunnerTests',
  );
}
